FROM amazoncorretto:17
# EXPOSE 8761
ADD target/huanying-restaurant-eureka-server-0.0.1-SNAPSHOT.jar huanying-restaurant-eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "huanying-restaurant-eureka-server-0.0.1-SNAPSHOT.jar"]