FROM amazoncorretto:17
ADD target/huanying-restaurant-api-gateway-0.0.1-SNAPSHOT.jar huanying-restaurant-api-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "huanying-restaurant-api-gateway-0.0.1-SNAPSHOT.jar"]