FROM amazoncorretto:17
ADD target/huanying-restaurant-order-items-0.0.1-SNAPSHOT.jar huanying-restaurant-order-items-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "huanying-restaurant-order-items-0.0.1-SNAPSHOT.jar"]