server:
  port: 8080
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: path
  application:
    name: api-gateway
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin 
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowed-headers: "*" 
    routes:
    - id: HuanyingReservation
      uri: lb://RESERVATION-SERVICE
      predicates:
      - Path=/reservations/**
    - id: HuanyingOrders
      uri: lb://ORDER-ITEMS-SERVICE
      predicates:
      - Path=/order-items/**

      
