FROM amazoncorretto:17
ADD target/huanying-restarant-reservation-0.0.1-SNAPSHOT.jar huanying-restarant-reservation-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "huanying-restarant-reservation-0.0.1-SNAPSHOT.jar"]